name: Norton
favicon: null
layout_spectrum: 0.24801054853014648
typography_spectrum: 0.899497743928805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45643229968845844
  lightness: 0.42987408908084035
  saturation: 0.15283993841148913
  rhythmicContrast: 0.8195740154478699
purpose: []
